# Generated by Django 4.1.7 on 2023-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advertisement_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
